---
- name: Playbook - Install figlet
  hosts: planetexpress:!farnsworth
  connection: ssh
  gather_facts: yes

  tasks:
  - name: using apt to install figlet
    apt:
        name: figlet
        state: present
    become: yes
