
---

- name: Install EPEL libraries in YUM
  hosts: planetexpress
  become: yes

  tasks:
   - name: "Install epel-release"
     yum:
      name: epel-release
      state: present
     when: ansible_distribution == "Centos"

   - name: "Update yum repos and Install packages X"
     yum:
      update_cache: True
      name:
         - fail2ban
         - moon-buggy
      state: latest
     when:ansible_distribution == "Centos"
