---
- name: Playbook - Uninstall figlet
  hosts: planetexpress:!farnsworth
  connection: ssh

  tasks:
  - name: using apt to remove figlet
    apt:
        name: figlet
        state: absent
    become: yes
