---
- name: Target Planet Express Hosts except bender and farnsworth
  hosts: planetexpress:!farnsworth:bender

  tasks:
  - name: Uninstall example apps [figlet, cowsay, bastet] using apt
    apt:
         pkg:
           - figlet
           - cowsay
           - bastet
         state: absent
    become: yes
