---
- name: Target Planet Express Hosts except bender and farnsworth
  hosts: planetexpress:!farnsworth:bender
  connection: ssh
  gather_facts: yes

  tasks:
  - name: Uninstall figlet, cowsay, bastet using apt
    apt:
         pkg:
           - figlet
           - cowsay
           - bastet
         state: absent
    become: yes
