
---
- name: Get-URL Download the Protected File
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  - name: Access the Wbsite and make sure the URL is live
    uri:
            method: GET
            url: http://10.10.2.4/admin/secure.txt
            status_code: 200
            return_content: yes
            url_username: sammy
            url_password: larry
    register: validateurl

  - name: Show that the content was still retrieved
    debug:
            var: validateurl.content

  - name: Put secret content into a file
    copy:
        content: "{{ validateurl.content }}"
        dest: ~/ansible-downloaded-the-secret-file.txt
